 const prayerData = {
  "1": { title: "Dấu Thánh Giá", category: "Kinh Căn Bản", content: "Nhân danh Cha và Con và Thánh Thần. Amen." },

  "2": { title: "Kinh Truyền Tin", category: "Kinh Sáng", content: "Chưa tìm ra kinh" },

  "3": { title: "Kinh Nữ Vương Thiên Đàng", category: "Mùa Phục Sinh", content: "Xướng: Lạy Nữ Vương Thiên Đàng hãy vui mừng – Alleluia\nĐáp: Vì đấng Mẹ đã đáng cưu mang trong lòng – Alleluia\nXướng: Người đã sống lại thật như lời đã phán hứa – Alleluia\nĐáp: Xin cầu cùng Chúa cho chúng con – Alleluia\nXướng: Lạy Nữ Đồng Trinh Maria hãy hỉ hoan khoái lạc – Alleluia\nĐáp: Vì Chúa đã sống lại thật – Alleluia" },

  "4": { title: "Kinh Đức Chúa Thánh Thần", category: "Kinh Căn Bản", content: "Chúng con lạy ơn Đức Chúa Thánh Thần, thiêng liêng sáng láng vô cùng, chúng con xin Đức Chúa Thánh Thần xuống đầy lòng chúng con, là kẻ tin cậy Đức Chúa Trời, và đốt lửa kính mến Dức Chúa Trời trong lòng chúng con; chúng con xin Đức Chúa Trời cho Đức Chúa Thánh Thần xuống.\nSửa lại mọi sự trong ngoài chúng con.Chúng con cầu cùng Đức Chúa Trời, xưa đã cho Đức Chúa Thánh Thần xuống soi lòng dạy dỗ các Thánh Tông Đồ, thì rày chúng con cũng xin Đức Chúa Trời cho Đức Chúa Thánh Thần lại xuống an ủi dạy dỗ chúng con làm những việc lành, vì công nghiệp vô cùng Đức Chúa Giêsu Kitô là Chúa chúng con. Amen." },

  "5": { title: "Kinh Sấp Mình", category: "Kinh Tối", content: "Lạy Chúa, con sấp mình xuống trước mặt Chúa. Con tin thật Chúa ở khắp mọi nơi, thông biết mọi sự, hằng xem thấy con, hằng nghe lời con cầu nguyện. Xin Chúa rất nhân từ hãy đoái xem sự nghèo ngặt con và nhận lời con nguyện. Lạy Chúa xin hãy mở miệng lưỡi con ra, thì con sẽ cao rao những lời ngợi khen Chúa." },

  "6": { title: "Kinh Thờ Lạy", category: "Kinh Tối", content: "Lạy Chúa, con là vật phàm hèn cùng là không trước mặt Chúa, con hết lòng thờ lạy và nhận thật Chúa là đầu cội rễ mọi sự, là cùng sau hết mọi loài; Chúa đã dựng nên con cùng thật là Chúa nữa, thì con xin dâng linh hồn và xác cùng mọi sự trong ngoài con ở trong tay Chúa. Amen." },

  "7": { title: "Kinh Đội Ơn", category: "Kinh Tối", content: "Lạy Chúa, con đội ơn Chúa vì những ơn lành Chúa đã ban cho con xưa nay, nhất là đã dựng nên con và cho Con Chúa chịu chết mà cứu chuộc con, lại chọn lấy con làm con Hội Thánh nữa. Amen." },

  "8": { title: "Kinh Tin", category: "Nhân Đức Đối Thần", content: "Lạy Chúa, con tin thật có một Đức Chúa Trời là Đấng thưởng phạt vô cùng.  Con lại tin thật Đức Chúa Trời có Ba Ngôi, mà Ngôi Thứ Hai đã xuống thế làm Người, chịu nạn chịu chết mà chuộc tội cho thiên hạ.  Bấy nhiêu điều ấy cùng các điều Hội Thánh dạy thì con tin vững vàng, vì Chúa là Đấng thông minh và chân thật vô cùng đã phán truyền cho Hội Thánh.  Amen" },

  "9": { title: "Kinh Cậy", category: "Nhân Đức Đối Thần", content: "Lạy Chúa , con trông cậy vững vàng, vì công nghiệp Đức Chúa Giêsu thì Chúa sẽ ban ơn cho con giữ đạo nên ở đời này, cho ngày sau được lên thiên đàng xem thấy mặt Đức Chúa Trời hưởng phúc đời đời, vì Chúa là đấng phép tắc và lòng lành vô cùng đã phán hứa sự ấy chẳng có lẽ nào sai được.  Amen." },

  "10": { title: "Kinh Mến", category: "Nhân Đức Đối Thần", content: "Lạy Chúa , con kính mến Chúa hết lòng hết sức trên hết mọi sự, vì Chúa là Đấng trọn tốt trọn lành vô cùng, lại vì Chúa, thì con thương yêu người ta như mình con vậy.  Amen." },

  "11": { title: "Kinh Lạy Cha", category: "Kinh Căn Bản", content: "Lạy Cha chúng con ở trên trời, chúng con nguyện Danh Cha cả sáng, nước Cha trị đến, ý Cha thể hiện dưới đất cũng như trên trời.Xin Cha cho chúng con hôm nay lương thực hằng ngày, và tha nợ chúng con, như chúng con cũng tha kẻ có nợ chúng con. Xin chớ để chúng con sa chước cám dỗ, nhưng cứu chúng con cho khỏi sự dữ. Amen" },

  "12": { title: "Kinh Kính Mừng", category: "Kinh Căn Bản", content: "Kính mừng Maria đầy ơn phúc Đức Chúa Trời ở cùng Bà, Bà có phúc lạ hơn mọi người nữ, và Giêsu con lòng Bà gồm phúc lạ.Thánh Maria Đức Mẹ Chúa Trời cầu cho chúng con là kẻ có tội khi này và trong giờ lâm tử. Amen" },

  "13": { title: "Kinh Sáng Danh", category: "Kinh Căn Bản", content: "Sáng Danh Đức Chúa Cha, và Đức Chúa Con, và Đức Chúa Thánh Thần, như đã có trước vô cùng, và bây giờ, và hằng có, và đời đời chẳng cùng. Amen." },

  "14": { title: "Kinh Tin Kính (Sứ Đồ)", category: "Kinh Căn Bản", content: "Tôi tin kính Đức Chúa Trời là Cha phép tắc vô cùng dựng nên trời đất.\nTôi tin kính Đức Chúa GiêSu Kitô là con một Đức Chúa Cha cùng là Chúa chúng tôi; bởi phép Đức Chúa Thánh Thần mà người xuống thai, sinh bởi Bà Maria đồng trinh; chịu nạn đời quan Phong-xi-ô Phi-la-tô, chịu đóng đanh trên cây Thánh Giá, chết và táng xác, xuống ngục tổ tông, ngày thứ ba bởi trong kẻ chết sống lại; lên trời ngự bên hữu Đức Chúa Cha phép tắc vô cùng; ngày sau bởi trời lại xuống phán xét kẻ sống và kẻ chết.\nTôi tin kính Đức Chúa Thánh Thần; tôi tin có hội Thánh hằng có ở khắp thế này, các Thánh thông công; tôi tin phép tha tội; tôi tin xác loài người ngày sau sống lại; tôi tin hằng sống vậy, Amen." },

  "15": { title: "Kinh Thú Nhận", category: "Phụng Vụ", content: "Tôi thú nhận cùng Thiên Chúa toàn năng và cùng anh chị em. Tôi đã phạm tội nhiều trong tư tưởng, lời nói việc làm, và những điều thiếu sót. Lỗi tại tôi, lỗi tại tôi, lỗi tại tôi mọi đàng. Vì vậy tôi xin Ðức Bà Maria trọn đời đồng trinh, các thiên thần, các thánh, và anh chị em khẩn cầu cho tôi trước tòa Thiên Chúa, Chúa chúng ta. Amen." },

  "16": { title: "Kinh Ăn Năn Tội", category: "Kinh Căn Bản", content: "Lạy Chúa , Chúa là Đấng trọn tốt trọn lành vô cùng. Chúa đã dựng nên con, và cho Con Chúa ra đời chịu nạn chịu chết vì con, mà con đã cả lòng phản nghịch lỗi nghĩa cùng Chúa, thì con lo buồn đau đớn, cùng chê ghét mọi tội con trên hết mọi sự; con dốc lòng chừa cải, và nhờ ơn Chúa thì con sẽ lánh xa dịp tội cùng làm việc đền tội cho xứng. Amen." },

  "17": { title: "Kinh Phù Hộ", category: "Đức Mẹ", content: "Chúng con thờ lạy ngợi khen Chúa là Đấng có phép tắc vô cùng, đã thương để chúng con đến sớm mai nay, thì xin Chúa xuống ơn phù hộ cho chúng con trót ngày hôm nay, khỏi sa phạm tội gì. Lại xin Chúa sửa sự lo, lời nói, việc làm chúng con hằng nên trọn lành theo ý Chúa; vì công nghiệp Đức Chúa Giêsu, là Đấng hằng sống hằng trị cùng Đức Chúa Cha và Đức Chúa Con và Đức Chúa Thánh Thần đời đời chẳng cùng. Amen." },

  "18": { title: "Kinh Sáng Soi", category: "Trước Khi Học", content: "Cúi xin Chúa sáng soi cho chúng con được biết việc phải làm, cùng khi làm xin Chúa giúp đỡ cho mỗi kinh mỗi việc chúng con, từ khởi sự cho đến hoàn thành đều nhờ bởi ơn Chúa. Amen." },

  "19": { title: "Kinh Thánh Thiên Thần Bản Mệnh", category: "Kinh Cá Nhân", content: "Đang tìm kinh..." },

  "20": { title: "Kinh Lạy Nữ Vương", category: "Đức Mẹ", content: "Lạy Nữ Vương Mẹ nhân lành, làm cho chúng con được sống, được vui, được cậy. Thân lạy Mẹ, chúng con, con cháu E-và ở chốn khách đầy kêu đến cùng Bà. Chúng con ở nơi khóc lóc than thở kêu khẩn Bà thương. Hỡi ôi! Bà là Chúa bầu chúng con, xin ghé mặt thương xem chúng con. Đến sau khỏi đày, xin cho chúng con được thấy Đức Chúa Giêsu, Con lòng Bà gồm phúc lạ." },

  "21": { title: "Kinh Trước Khi Xét Mình", category: "Xét Mình", content: "Lạy Chúa là áng sáng linh hồn con, xin soi sáng cho con được biết mọi tội con đã phạm trong ngày hôm nay, về tư tưởng, lời nói, việc làm điều gì lỗi nghĩa cùng Chúa. Con xin Chúa vì công nghiệp Đức Chúa Giêsu ban ơn cho con được ăn năn ghét tội, cùng quyết tâm chừa thật. Amen" },

  "22": { title: "Kinh Hãy Nhớ", category: "Đức Mẹ", content: "Lạy Thánh Nữ Đồng Trinh Maria là Mẹ rất nhân từ, xin hãy nhớ xưa nay chưa từng nghe có người nào chạy đến cùng Đức Mẹ xin bầu chữa cứu giúp mà Đức Mẹ từ bỏ chẳng nhậm lời. Nhân vì sự ấy, con hết lòng trông cậy than van chạy đến sấp mình xuống dưới chân Đức Mẹ là Nữ Đồng Trinh trên hết các kẻ đồng trinh, xin Đức Mẹ đoái đến con là kẻ tội lỗi. Lạy Mẹ là Mẹ Chúa Cứu Thế, xin chớ bỏ lời con kêu xin, một dủ lòng thương và nhậm lời con cùng. Amen" },

  "23": { title: "Kinh Phó Dâng", category: "Kinh Tối", content: "Lạy Chúa con, con xin phó dâng linh hồn và xác con ở tay Chúa con. Chúa đã phù hộ con ban ngày, thì xin Chúa cũng gìn giữ con ban đêm, kẻo sa phạm tội gì mất lòng Chúa hay là chết tươi ăn năn tội chẳng kịp. Chớ gì sống chết con được giữ một lòng kính mến Chúa luôn. Amen." },

  "24": { title: "Kinh Cám Ơn", category: "Kinh Tối", content: "Con cám ơn Đức Chúa trời là Chúa lòng lành vô cùng, chẳng bỏ con, chẳng để con không đời đời mà lại sinh ra con, cho con được làm người, cùng hằng gìn giữ con hằng che chở con, lại cho ngôi hai xuống thế làm người, chuộc tội chịu chết trên cây thánh giá vì con, lại cho con được đạo thánh Đức Chúa Trời cũng chịu nhiều ơn nhiều phép hội thánh nữa, và đã cho phần xác con (ngày / đêm) hôm nay được mọi sự lành, lại cứu lấy con kẻo phải chết tươi ăn năn tội chẳng kịp. Vậy các thánh ở trên nước thiên đàng cám ơn Đức Chúa Trời thế nào thì con cùng hợp cùng các thánh mà dâng chúa con cùng cám ơn như vậy, Amen." },

  "25": { title: "Kinh Trông Cậy", category: "Nhân Đức", content: "Chúng con trông cậy rất thánh Đức Mẹ Chúa Trời, xin chớ chê chớ bỏ lời chúng con nguyện trong cơn gian nan thiếu thốn. Đức Nữ Đồng Trinh hiển vinh sáng láng\nThưa: Hằng chữa chúng con cho khỏi mọi sự dữ. Amen.\nCác câu lạy\n Lạy rất thánh Trái Tim Đức Chúa Giêsu.\nThương xót chúng con.\nLạy Trái Tim cực Thánh cực tịnh Rất Thánh Đức Bà Maria.\nCầu cho chúng con.\nLạy Ông thánh Giuse là bạn thanh sạch Đức Bà Maria trọn đời đồng trinh.\nCầu cho chúng con.\nCác Thánh Tử Vì Đạo nước Việt Nam\nCầu cho chúng con.\nNữ Vương ban sự bằng an.\nCầu cho chúng con.\nNhân Danh Cha và Con và Thánh Thần Amen." },

  "26": { title: "Các Lời Nguyện Tắt", category: "Nguyện Tắt", content: "Đang tìm kinh..." },

  "27": { title: "10 Điều Răn", category: "Giáo Lý", content: "Đạo Đức Chúa Trời có mười điều răn:\nThứ nhất: Thờ phượng một Đức Chúa Trời và kính mến Người trên hết mọi sự.\nThứ hai: Chớ kêu tên Đức Chúa Trời vô cớ.\nThứ ba: Giữ ngày Chúa nhật\nThứ bốn: Thảo kính cha mẹ.\nThứ năm: Chớ giết người.\nThứ sáu: Chớ làm sự dâm dục.\nThứ bảy: Chớ lấy của người.\nThứ tám: Chớ làm chứng dối.\nThứ chín: Chớ muốn vợ chồng người.\nThứ mười: Chớ tham của người.\nMười điều răn ấy tóm về hai này mà chớ:\nTrước kính mến một Đức Chúa Trời trên hết mọi sự, sau lại yêu người như mình ta vậy. Amen." },

  "28": { title: "6 Điều Răn Hội Thánh", category: "Giáo Lý", content: "Hội Thánh có sáu điều răn:\nThứ nhất, xem lễ ngày Chủ nhật, cùng các ngày lễ buộc.\nThứ hai, chớ làm việc xác ngày Chủ nhật cùng các ngày lễ buộc.\nThứ ba, xưng tội trong một năm ít là một lần.\nThứ bốn, chịu Mình Thánh Đức Chúa Giêsu trong mùa Phục Sinh.\nThứ năm, giữ chay những ngày Hội Thánh buộc.\nThứ sáu, kiêng thịt ngày thứ sáu, cùng những ngày khác Hội Thánh dạy." },

  "29": { title: "7 Phép Bí Tích", category: "Giáo Lý", content: "Đạo Thánh Đức Chúa Trời có bảy phép Bí Tích;\nThứ nhất: là phép Rửa tội.\nThứ hai: là phép Thêm sức.\nThứ ba: là phép Mình Thánh Chúa.\nThứ bốn: là phép Giải tội.\nThứ năm: là phép Xức dầu thánh.\nThứ sáu: là phép Truyền chức thánh.\nThứ bảy: là phép Hôn phối." },

  "30": { title: "14 Mối Thương Người", category: "Luân Lý", content: "Thương người có mười bốn mối\nThương xác bảy mối:\nThứ nhất, cho kẻ đói ăn.\nThứ hai, cho kẻ khát uống.\nThứ ba, cho kẻ rách rưới ăn mặc.\nThứ bốn, viếng kẻ liệt cùng kẻ tù rạc.\nThứ năm, cho khách đỗ nhà.\nThứ sáu, chuộc kẻ làm tôi.\nThứ bảy, chôn xác kẻ chết.\n\n Thương linh hồn bảy mối:\nThứ nhất, lấy lời lành mà khuyên người.\nThứ hai, mở dậy kẻ mê muội.\nThứ ba, yên ủi kẻ âu lo.\nThứ bốn, răn bảo kẻ có tội.\nThứ năm, tha kẻ dể ta.\nThứ sáu, nhịn kẻ mất lòng ta.\nThứ bảy, cầu cho kẻ sống và kẻ chết." },

  "31": { title: "7 Mối Tội Đầu", category: "Luân Lý", content: "Cải tội bảy mối có bảy đức:\nThứ nhất: Khiêm nhường, chớ kiêu ngạo.\nThứ hai: Rộng rãi, chớ hà tiện.\nThứ ba: Giữ mình sạch sẽ, chớ mê dâm dục.\nThứ bốn: Hay nhịn, chớ hờn giận.\nThứ năm: Kiêng bớt, chớ mê ăn uống.\nThứ sáu: Yêu người, chớ ghen ghét.\nThứ bảy: Siêng năng việc Đức Chúa Trời, chớ làm biếng." },

  "32": { title: "Phúc Thật 8 Mối", category: "Tin Mừng", content: "Phúc thật tám mối:\nThứ nhất: ai có lòng khó khăn, ấy là phúc thật, vì chưng nước Đức Chúa Trời là của mình vậy.\nThứ hai: ai hiền lành, ấy là phúc thật, vì chưng sẽ được đất Đức Chúa Trời làm của mình vậy.\nThứ ba: ai khóc lóc, ấy là phúc thật, vì chưng sẽ được an ủi vậy.\nThứ bốn: ai khao khát nhân đức trọn lành, ấy là phúc thật, vì chưng sẽ được no đủ vậy.\nThứ năm: ai thương xót người, ấy là phúc thật, vì chưng mình sẽ được thương xót vậy.\nThứ sáu: ai giữ lòng sạch sẽ, ấy là phúc thật, vì chưng sẽ được thấy mặt Đức Chúa Trời vậy.\nThứ bảy: ai làm cho người hòa thuận, ấy là phúc thật, vì chưng sẽ được gọi là con Đức Chúa Trời vậy.\nThứ tám: ai chịu khốn nạn vì đạo ngay, ấy là phúc thật, vì chưng nước Đức Chúa Trời là của mình vậy." },

  "33": { title: "Năm Sự Vui", category: "Mân Côi", content: "Thứ nhất thì ngắm: Thiên thần truyền tin cho Đức Bà chịu thai. Ta hãy xin cho được ở khiêm nhường.\nThứ hai thì ngắm: Đức Bà đi viếng bà thánh Isave. Ta hãy xin cho được lòng yêu người.\nThứ ba thì ngắm: Đức Bà sinh Đức Chúa Giêsu nơi hang đá. Ta hãy xin cho được lòng khó khăn.\nThứ bốn thì ngắm: Đức Bà dâng Đức Chúa Giêsu trong đền thánh. Ta hãy xin cho được vâng lời chịu lụy.\nThứ năm thì ngắm: Đức Bà tìm được Đức Chúa Giêsu trong đền thánh. Ta hãy xin cho được giữ nghĩa cùng Chúa luôn." },

  "34": { title: "Năm Sự Sáng", category: "Mân Côi", content: "Thứ nhất thì ngắm: Đức Chúa Giêsu chịu phép Rửa tại sông Giođan. Ta hãy xin cho được sống xứng đáng là con cái Chúa.\nThứ hai thì ngắm: Đức Chúa Giêsu dự tiệc cưới Cana. Ta hãy xin cho được vững tin vào quyền năng của Ngài.\nThứ ba thì ngắm: Đức Chúa Giêsu rao giảng Nước Trời và kêu gọi sám hối. Ta hãy xin cho được hoán cải và đón nhận Tin Mừng.\nThứ tư thì ngắm: Đức Chúa Giêsu biến hình trên núi. Ta hãy xin cho được lắng nghe và thực hành lời Chúa.\nThứ năm thì ngắm: Đức Chúa Giêsu lập bí tích Thánh Thể. Ta hãy xin cho được năng kết hợp cùng Chúa Giêsu Thánh Thể." },

  "35": { title: "Năm Sự Thương", category: "Mân Côi", content: "Thứ nhất thì ngắm: Đức Chúa Giêsu lo buồn đổ mồ hôi máu. Ta hãy xin cho được ăn năn tội nên.\nThứ hai thì ngắm: Đức Chúa Giêsu chịu đánh đòn. Ta hãy xin cho được hãm mình chịu khó bằng lòng.\nThứ ba thì ngắm: Đức Chúa Giêsu chịu đội mão gai. Ta hãy xin cho được chịu mọi sự sỉ nhục bằng lòng.\nThứ tư thì ngắm: Đức Chúa Giêsu vác cây Thánh Giá. Ta hãy xin cho được vác Thánh Giá theo chân Chúa.\nThứ năm thì ngắm: Đức Chúa Giêsu chịu chết trên cây Thánh Giá. Ta hãy xin cho được đóng đinh tính xác thịt vào Thánh Giá Chúa." },

  "36": { title: "Năm Sự Mừng", category: "Mân Côi", content: "Thứ nhất thì ngắm: Đức Chúa Giêsu sống lại. Ta hãy xin cho được sống lại thật về phần linh hồn.\nThứ hai thì ngắm: Đức Chúa Giêsu lên trời. Ta hãy xin cho được lòng ái mộ những sự trên trời.\nThứ ba thì ngắm: Đức Chúa Thánh Thần hiện xuống. Ta hãy xin cho được lòng đầy dẫy mọi ơn Đức Chúa Thánh Thần.\nThứ tư thì ngắm: Đức Chúa Trời cho Đức Bà lên trời. Ta hãy xin ơn chết lành trong tay Đức Mẹ.\nThứ năm thì ngắm: Đức Chúa Trời thưởng Đức Mẹ trên trời. Ta hãy xin Đức Mẹ phù hộ cho ta được thưởng cùng Đức Mẹ trên nước thiên đàng." },

  "37": { title: "Kinh Dọn Mình Chịu Lễ", category: "Thánh Thể", content: "Lạy Chúa Giêsu, con tin thật Chúa đang ngự trong Bí Tích Thánh Thể. Chúa là Thiên Chúa thật và là người thật, đã trở nên thần lương nuôi sống chúng con trên đường về quê trời.\nChúa muốn ở trong con, và con cũng ước ao rước Chúa vào lòng, để được ở lại trong Chúa. Nhưng con biết, mình còn nhiều tội lỗi, chẳng đáng Chúa đến thăm.Xin Chúa tẩy sạch tâm lòng con, để con nên trong trắng. Xin Chúa mở rộng hồn con, để con đừng từ chối Chúa điều gì.\nLạy Chúa Giêsu, con yêu mến Chúa lắm, xin Chúa mau đến với con. Lạy Mẹ Maria và Thánh Cả Giuse, xin giúp con dọn mình xứng đáng đón rước Chúa Giêsu. Amen." },

  "38": { title: "Kinh Cám Ơn Hiệp Lễ", category: "Thánh Thể", content: "Con thờ lạy Chúa chí tôn,\nĐoái thương ngự xuống lòng con giờ này.\nHợp cùng trời đất muôn loài,\nHợp cùng sông biển, cỏ cây, núi đồi;\nHợp cùng thần thánh trên trời,\nCon ca tụng Chúa đời đời hiển vinh.\nTạ ơn Chúa rất nhân lành,\nĐã thương ban Thịt Máu Mình nuôi con.\nCon dâng cho Chúa xác hồn,\nViệc làm, đời sống, vui buồn, khổ đau.\nNguyện xin Mình Thánh nhiệm mầu;\nGiữ con hồn xác trước sau an lành.\nCho con giữ đạo nhiệt thành,\nSau lên hưởng phúc trường sinh thiên đàng.\nXin phù hộ Đức Giáo Hoàng,\nCùng hàng giáo phẩm và đoàn giáo dân.\nXin ban xuống mọi ơn cần,\nCho người thân thuộc xa gần của con.\nXin thương kẻ khuất, người còn,\nXin cho tổ quốc con muôn phúc lành.\nCho người tội lỗi sửa mình,\nCho người đau khổ cậy tin không sờn.\nQuyết tâm, con mến Chúa hơn;\nTránh xa tội lỗi, giữ ơn trung thành.\nQuyết tâm, con sống trọn lành;\nXứng con Cha Cả hiển vinh trên trời." }};

  export default prayerData;