const giaoLyBook = {
  id: "giao-ly-du-tong",
  title: "Giáo Lý Dự Tòng",

  chapters: [
    {
      id: "bai-1",
      order: 1,
      title: "LOÀI NGƯỜI TÌM KIẾM THIÊN CHÚA",
      slug: "loai-nguoi-tim-kiem-thien-chua",
    },
    {
      id: "bai-2",
      order: 2,
      title: "THIÊN CHÚA NÓI VỚI LOÀI NGƯỜI",
      slug: "thien-chua-noi-voi-loai-nguoi",
    },
    {
      id: "bai-3",
      order: 3,
      title: "ĐÓN NHẬN LỜI CHÚA",
      slug: "don-nhan-loi-chua",
    },
    {
      id: "bai-4",
      order: 4,
      title: "THIÊN CHÚA DỰNG NÊN TRỜI ĐẤT MUÔN VẬT VÀ LOÀI NGƯỜI",
      slug: "thien-chua-dung-nen-troi-dat",
    },
    {
      id: "bai-5",
      order: 5,
      title: "LOÀI NGƯỜI SA NGÃ – TỘI – LỜI HỨA CỨU ĐỘ",
      slug: "loai-nguoi-sa-nga-toi-loi-hua-cuu-do",
    },
    {
      id: "bai-6",
      order: 6,
      title: "THIÊN CHÚA CHỌN CÁC TỔ PHỤ VÀ THÀNH LẬP DÂN RIÊNG",
      slug: "thien-chua-chon-cac-to-phu",
    },
    {
      id: "bai-7",
      order: 7,
      title: "THIÊN CHÚA THIẾT LẬP GIAO ƯỚC VÀ BAN LỀ LUẬT",
      slug: "thien-chua-thiet-lap-giao-uoc",
    },
    {
      id: "bai-8",
      order: 8,
      title: "THIÊN CHÚA CHỌN GỌI CÁC NGÔN SỨ",
      slug: "thien-chua-chon-goi-cac-ngon-su",
    },
    {
      id: "bai-9",
      order: 9,
      title: "CHÚA GIÊSU SINH RA",
      slug: "chua-giesu-sinh-ra",
    },
    {
      id: "bai-10",
      order: 10,
      title: "CHÚA GIÊSU SỐNG ẨN DẬT",
      slug: "chua-giesu-song-an-dat",
    },
    {
      id: "bai-11",
      order: 11,
      title: "CHÚA GIÊSU RAO GIẢNG NƯỚC THIÊN CHÚA",
      slug: "chua-giesu-rao-giang",
    },
    {
      id: "bai-12",
      order: 12,
      title: "CHÚA GIÊSU DẠY TA VỀ CHÚA BA NGÔI",
      slug: "chua-giesu-day-ve-chua-ba-ngoi",
    },
    {
      id: "bai-13",
      order: 13,
      title: "TÔN THỜ THIÊN CHÚA",
      slug: "ton-tho-thien-chua",
    },
    {
      id: "bai-14",
      order: 14,
      title: "TIN – CẬY – MẾN – THỜ PHƯỢNG",
      slug: "tin-cay-men-tho-phuong",
    },
    {
      id: "bai-15",
      order: 15,
      title: "SỐNG HIẾU THẢO",
      slug: "song-hieu-thao",
    },
    {
      id: "bai-16",
      order: 16,
      title: "TÔN TRỌNG SỰ SỐNG – SỐNG TRONG SẠCH",
      slug: "ton-trong-su-song-song-trong-sach",
    },
    {
      id: "bai-17",
      order: 17,
      title: "SỐNG CÔNG BÌNH, SỐNG THEO SỰ THẬT",
      slug: "song-cong-binh-song-theo-su-that",
    },
    {
      id: "bai-18",
      order: 18,
      title: "TINH THẦN MỚI TRONG LUẬT CŨ",
      slug: "tinh-than-moi-trong-luat-cu",
    },
    {
      id: "bai-19",
      order: 19,
      title: "CHÚA GIÊSU CHỊU CHẾT VÀ SỐNG LẠI",
      slug: "chua-giesu-chiu-chet-va-song-lai",
    },
    {
      id: "bai-20",
      order: 20,
      title: "CHÚA GIÊSU BAN CHÚA THÁNH THẦN CHO HỘI THÁNH",
      slug: "chua-giesu-ban-chua-thanh-than",
    },
    {
      id: "bai-21",
      order: 21,
      title: "CHÚA THÁNH THẦN – HỒN SỐNG CỦA HỘI THÁNH",
      slug: "chua-thanh-than-hon-song-cua-hoi-thanh",
    },
    {
      id: "bai-22",
      order: 22,
      title: "MẦU NHIỆM HỘI THÁNH",
      slug: "mau-nhiem-hoi-thanh",
    },
    {
      id: "bai-23",
      order: 23,
      title: "CÁC ĐẶC TÍNH CỦA HỘI THÁNH CÔNG GIÁO",
      slug: "cac-dac-tinh-cua-hoi-thanh",
    },
    {
      id: "bai-24",
      order: 24,
      title: "CÁC CHỨC VỤ CỦA HỘI THÁNH",
      slug: "cac-chuc-vu-cua-hoi-thanh",
    },
    {
      id: "bai-25",
      order: 25,
      title: "ĐỨC MARIA TRONG MẦU NHIỆM HỘI THÁNH",
      slug: "duc-maria-trong-mau-nhiem-hoi-thanh",
    },
    {
      id: "bai-26",
      order: 26,
      title: "NĂM PHỤNG VỤ",
      slug: "nam-phung-vu",
    },
    {
      id: "bai-27",
      order: 27,
      title: "ƠN CHÚA VÀ BÍ TÍCH",
      slug: "on-chua-va-bi-tich",
    },
    {
      id: "bai-28",
      order: 28,
      title: "BÍ TÍCH RỬA TỘI",
      slug: "bi-tich-rua-toi",
    },
    {
      id: "bai-29",
      order: 29,
      title: "BÍ TÍCH THÊM SỨC",
      slug: "bi-tich-them-suc",
    },
    {
      id: "bai-30",
      order: 30,
      title: "THÁNH LỄ",
      slug: "thanh-le",
    },
    {
      id: "bai-31",
      order: 31,
      title: "BÍ TÍCH GIẢI TỘI",
      slug: "bi-tich-giai-toi",
    },
    {
      id: "bai-32",
      order: 32,
      title: "BÍ TÍCH XỨC DẦU BỆNH NHÂN",
      slug: "bi-tich-xuc-dau-benh-nhan",
    },
    {
      id: "bai-33",
      order: 33,
      title: "BÍ TÍCH TRUYỀN CHỨC THÁNH",
      slug: "bi-tich-truyen-chuc-thanh",
    },
    {
      id: "bai-34",
      order: 34,
      title: "BÍ TÍCH HÔN PHỐI",
      slug: "bi-tich-hon-phoi",
    },
    {
      id: "bai-35",
      order: 35,
      title: "TỨ CHUNG",
      slug: "tu-chung",
    },
    {
      id: "bai-36",
      order: 36,
      title: "TRỜI MỚI, ĐẤT MỚI",
      slug: "troi-moi-dat-moi",
    },
  ],
};