// src/data/events.js
export const eventData = [
  {
    id: 1,
    slug: "dai-le-kinh-thanh-quan-thay",
    title: "Đại lễ Kính Thánh Quan Thầy Giáo Xứ",
    date: "2026-06-29",
    time: "18:00",
    location: "Khuôn viên nhà thờ",
    category: "Đại lễ",
    images: [
      "https://images.unsplash.com/photo-1548625149-fc4a29cf7092?q=80&w=1000",
      "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?q=80&w=1000",
    ],
    desc: "Mừng kính trọng thể Thánh Phêrô và Thánh Phaolô Tông đồ.",
    fullContent:
      "Năm 1745, thời vua Cảnh Hưng, giáo dân Cổ Việt có liên đới dòng tộc với dân Đồng Quan. Hai ông Tuần Lương và Huyện Kiêm – anh em ruột - có thông gia với ông Lê Cảnh Thức ở xứ Cổ Việt, nhờ đó các ông đã được đón nhận đức tin. Ông Trần Văn Kiêm có bằng Đồng Sĩ Phủ, làm nghị viện Bắc Kỳ, nên có cơ hội chuyển chi họ mình về mảnh đất mới là Đồng Quan để sinh sống.Không biết họ Đồng Quan được thành lập năm nào, nhưng ngôi nhà thờ đầu tiên được tiền nhân xây vào năm 1752. Khi Giáo xứ Cổ Việt được thành lập (1793), Giáo họ Đồng Quan thường xuyên được đón cha về dâng lễ. Tới năm 1888, Giáo xứ Thân Thượng được thành lập, họ Đồng Quan được cắt về giáo xứ mới này.Năm 1889, số giáo dân ngày một đông nên nhà thờ được xây dựng lại.Năm 1911, Đức cha Phêrô Munagorri Trung đã tách họ Đồng Quan và một số giáo họ khác để nâng lên hàng giáo xứ.Mặc dù nhà thờ được trùng tu hai lần vào năm 1954 và 1989, nhưng qua dòng thời gian, ngôi nhà thờ chẳng những đã xuống cấp mà lại còn rất chật hẹp. Năm 1997, Đức cha Phanxicô Xaviê Nguyễn Văn Sang đã cho phép xây dựng nhà thờ mới rộng rãi và bề thế hơn, được cắt băng khánh thành ngày 21/11/2000.",
  },
  {
    id: 2,
    slug: "khoa-giao-ly-hon-nhan-khoa-1",
    title: "Khóa Giáo lý Hôn nhân Khóa I - 2026",
    date: "2026-05-20",
    time: "19:30",
    location: "Phòng giáo lý tầng 2",
    category: "Giáo lý",
    images: [
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1000",
    ],
    desc: "Chuẩn bị nền tảng vững chắc cho đời sống hôn nhân Kitô giáo.",
    fullContent:
      "Chương trình gồm 12 buổi học về tâm lý, đức tin và kỹ năng sống.",
  },
  {
    id: 3,
    slug: "trung-thu-thieu-nhi",
    title: "Vui Tết Trung Thu Thiếu Nhi",
    date: "2026-09-15",
    time: "17:00",
    location: "Sân nhà xứ",
    category: "Thiếu nhi",
    images: [
      "https://images.unsplash.com/photo-1508672019048-805c876b67e2?q=80&w=1000",
    ],
    desc: "Đêm hội trăng rằm dành cho các em thiếu nhi trong giáo xứ.",
    fullContent: "Bao gồm múa lân, phát quà và sinh hoạt vui chơi tập thể.",
  },
  {
    id: 4,
    slug: "chuong-trinh-bac-ai-mua-chay",
    title: "Chương trình Bác Ái Mùa Chay",
    date: "2026-03-10",
    time: "08:00",
    location: "Giáo họ vùng sâu",
    category: "Bác ái",
    images: [
      "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?q=80&w=1000",
    ],
    desc: "Chia sẻ yêu thương đến các gia đình có hoàn cảnh khó khăn.",
    fullContent: "Quyên góp và trao quà cho 50 hộ gia đình nghèo.",
  },
  {
    id: 5,
    slug: "tinh-tam-gioi-tre",
    title: "Tĩnh tâm Giới Trẻ Mùa Vọng",
    date: "2026-12-05",
    time: "19:00",
    location: "Nhà nguyện",
    category: "Giới trẻ",
    images: [
      "https://images.unsplash.com/photo-1507692049790-de58290a4334?q=80&w=1000",
    ],
    desc: "Chuẩn bị tâm hồn đón mừng Chúa Giáng Sinh.",
    fullContent:
      "Chia sẻ Lời Chúa, cầu nguyện Taizé và lãnh nhận Bí tích Hòa giải.",
  },
  {
    id: 6,
    slug: "le-cau-cho-cac-linh-hon",
    title: "Thánh lễ Cầu cho các Linh hồn",
    date: "2026-11-02",
    time: "05:00",
    location: "Nghĩa trang giáo xứ",
    category: "Phụng vụ",
    images: [
      "https://images.unsplash.com/photo-1478146896981-b80fe463b330?q=80&w=1000",
    ],
    desc: "Hiệp thông cầu nguyện cho các linh hồn đã qua đời.",
    fullContent: "Thánh lễ và viếng nghĩa trang theo truyền thống Giáo Hội.",
  },
  {
    id: 7,
    slug: "sinh-hoat-ca-doan",
    title: "Sinh hoạt & Tuyển Ca viên mới",
    date: "2026-04-18",
    time: "20:00",
    location: "Phòng Ca đoàn",
    category: "Hội đoàn",
    images: [
      "https://images.unsplash.com/photo-1507838153414-b4b713384a76?q=80&w=1000",
    ],
    desc: "Mời gọi các bạn trẻ tham gia phục vụ trong Ca đoàn.",
    fullContent: "Gặp gỡ, chia sẻ và thử giọng các thành viên mới.",
  },
  {
    id: 8,
    slug: "le-chua-phuc-sinh",
    title: "Đại lễ Chúa Phục Sinh",
    date: "2026-04-05",
    time: "04:30",
    location: "Thánh đường",
    category: "Đại lễ",
    images: [
      "https://images.unsplash.com/photo-1523438885200-e635ba2c371e?q=80&w=1000",
    ],
    desc: "Cử hành phụng vụ trọng thể mừng Chúa sống lại.",
    fullContent: "Nghi thức Thắp nến Phục Sinh và Thánh lễ trọng thể.",
  },
];
